"""empty message

Revision ID: 2ddca2517753
Revises: eaff31ded9ac
Create Date: 2018-06-13 13:52:26.729182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddca2517753'
down_revision = 'eaff31ded9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('division_id', sa.Integer(), nullable=True))
    op.drop_constraint('employees_division_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'divisions', ['division_id'], ['id'])
    op.drop_column('employees', 'division')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('division', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_division_fkey', 'employees', 'divisions', ['division'], ['id'])
    op.drop_column('employees', 'division_id')
    # ### end Alembic commands ###
