"""empty message

Revision ID: 34d9641ee5b4
Revises: 90541f67ca95
Create Date: 2018-06-14 07:25:39.341392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d9641ee5b4'
down_revision = '90541f67ca95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_gender', table_name='employees')
    op.create_index(op.f('ix_employees_gender'), 'employees', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_gender'), table_name='employees')
    op.create_index('ix_employees_gender', 'employees', ['gender'], unique=True)
    # ### end Alembic commands ###
