"""empty message

Revision ID: 90541f67ca95
Revises: dd0160203d54
Create Date: 2018-06-14 05:36:27.687036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90541f67ca95'
down_revision = 'dd0160203d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_divisions_note', table_name='divisions')
    op.create_unique_constraint(None, 'divisions', ['note'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'divisions', type_='unique')
    op.create_index('ix_divisions_note', 'divisions', ['note'], unique=True)
    # ### end Alembic commands ###
